@baseUrl = http://localhost:8080
@token = MOwqmy6TKmANSy3OqjLribqYMfGBDDjeEn6gq5QF205374aa

### Выход из системы
# Требует токен авторизации. Удаляет текущий токен пользователя.
POST {{baseUrl}}/api/logout
Authorization: Bearer {{token}}


### Выход без токена (должна быть ошибка)
POST {{baseUrl}}/api/logout


