@baseUrl = http://localhost:8080
@token = dPmdiuhiWm7Tac5RfpX73RRIFinR2rCMxhwTwEuO908aa886

### Выход из системы
# Требует токен авторизации. Удаляет текущий токен пользователя.
POST {{baseUrl}}/api/logout
Authorization: Bearer {{token}}


### Выход без токена (должна быть ошибка)
POST {{baseUrl}}/api/logout


